databases:
  default:
    username: grafanau
    password: oracle
    url: demo-oracle-db:1521/XEPDB1
    queryTimeout: 5

metrics:
  default: default-metrics.toml
  custom:
    - /custom-metrics.toml
